rest_uri="https://my-<labuser>adb.eu-frankfurt-1.oraclecloudapps.com"
ords_user="labusername"
sensor_API="/sensorapi/"
speed_API="/wsapi/V1/kmh"
debug_level="15"
memory_treshold="2006000"
iterations="1000"
post_sleep_time="5"
net2_wifi_ssid="home"
net2_wifi_password="xxx"
net1_wifi_ssid="android"
net1_wifi_password="xxx"
